app = "voiddrop"
primary_region = "hkg"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 9876
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [[services.ports]]
    port = 9876
    handlers = []
